vim.api.nvim_set_var("mapleader", " ")
vim.api.nvim_command([[command! Q q!]])
vim.api.nvim_command([[command! QA qa!]])
vim.api.nvim_set_keymap("n", "\\", ".", { noremap = true })
vim.api.nvim_set_keymap("n", ".", "<Nop>", { noremap = true })
vim.api.nvim_set_keymap("n", "q", "<Nop>", { noremap = true })
vim.api.nvim_set_keymap("n", "Q", "<Nop>", { noremap = true })
vim.api.nvim_set_keymap("n", ";", ":", { noremap = true })
vim.api.nvim_set_keymap("n", ":", ":!", { noremap = true })
vim.api.nvim_set_keymap("n", "Y", "y$", { noremap = true })
vim.api.nvim_set_keymap("n", "N", "Nzzzv", { noremap = true })
vim.api.nvim_set_keymap("n", "n", "nzzzv", { noremap = true })
vim.api.nvim_set_keymap("i", ".", ".<C-g>u", { noremap = true })
vim.api.nvim_set_keymap("i", ",", ",<C-g>u", { noremap = true })
vim.api.nvim_set_keymap("i", ";", ";<C-g>u", { noremap = true })
vim.api.nvim_set_keymap("x", "<Tab>", ">gv", { noremap = true })
vim.api.nvim_set_keymap("x", "<S-Tab>", "<gv", { noremap = true })
vim.api.nvim_set_keymap("i", "jk", "<Esc>", { noremap = true })
vim.api.nvim_set_keymap("c", "jk", "<Esc>", { noremap = true })
vim.api.nvim_set_keymap("t", "jk", "<C-\\><C-N>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Space>", "<Nop>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Tab>", "<Cmd>bnext<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<S-Tab>", "<Cmd>bprevious<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader><Tab>", "<Cmd>buffer#<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>h", "<Cmd>wincmd h<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>j", "<Cmd>wincmd j<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>k", "<Cmd>wincmd k<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>l", "<Cmd>wincmd l<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>H", "<Cmd>wincmd H<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>J", "<Cmd>wincmd J<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>K", "<Cmd>wincmd K<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>L", "<Cmd>wincmd L<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader><BS>", "<Cmd>wincmd =<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>=", "<Cmd>vertical resize+5<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<Leader>-", "<Cmd>vertical resize-5<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("x", "J", "<Esc><Cmd>'<,'>m '>+1<CR>gv=gv", { noremap = true, silent = true })
vim.api.nvim_set_keymap("x", "K", "<Esc><Cmd>'<,'>m '<-2<CR>gv=gv", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "J", "<Cmd>move+1<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "K", "<Cmd>move-2<CR>", { noremap = true, silent = true })
