set -g default-terminal "screen-256color"
set -g base-index 1

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set-window-option -g mode-keys vi
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R
bind s split-window -v
bind v split-window -h
