export ZDOTDIR=$HOME/.config/zsh
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export EDITOR=nvim
export VISUAL=nvim
export TERM=xterm-256color
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PATH=$HOME/.local/bin:$PATH
export LESSHISTFILE=-
export KEYTIMEOUT=30
